---
repos:
# Core file quality checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-json
  - id: check-merge-conflict
  - id: check-added-large-files
    args: [--maxkb=500]
  - id: mixed-line-ending
    args: [--fix=lf]

# Python: Ruff for linting and formatting
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.12
  hooks:
  - id: ruff-check
    args: [--fix]
    files: ^(.*\.py|.*/executable_.*)$
  - id: ruff-format
    files: ^(.*\.py|.*/executable_.*)$


# YAML validation
- repo: https://github.com/adrienverge/yamllint
  rev: v1.37.1
  hooks:
  - id: yamllint
    args: [--format, parsable, --strict]

# PowerShell script analysis (local hook)
- repo: local
  hooks:
  - id: psscriptanalyzer
    name: PowerShell Script Analyzer
    entry: pwsh
    args: [-Command, "Invoke-ScriptAnalyzer", "-Path"]
    language: system
    files: \.(ps1|psm1|psd1)$
    stages: [manual]

# Markdown formatting
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.18.1
  hooks:
  - id: markdownlint-cli2
    args: [--fix]
    exclude: ^docs/external/
