[".bash_completion.d/complete_alias"]
    type = "file"
    url = "https://raw.githubusercontent.com/cykerway/complete-alias/master/complete_alias"
    refreshPeriod = "168h" # Refresh weekly

# Claude ultra-think command
[".claude/commands/ultra-think.md"]
    type = "file"
    url = "https://raw.githubusercontent.com/qdhenry/Claude-Command-Suite/main/.claude/commands/ultra-think.md"
    refreshPeriod = "168h" # Refresh weekly
