opencodeModels:
  work:
    title:
      model: anthropic/claude-sonnet-5
    compaction:
      model: anthropic/claude-sonnet-5
    general:
      model: anthropic/claude-sonnet-5
      variant: low
    explore:
      model: anthropic/claude-sonnet-5
      variant: low
    coder:
      model: anthropic/claude-sonnet-5
      variant: medium
    commit:
      model: anthropic/claude-sonnet-5
      variant: low
    researcher:
      model: anthropic/claude-sonnet-5
      variant: medium
    reviewer:
      model: anthropic/claude-opus-5
      variant: low
    upgradeAnalyst:
      model: anthropic/claude-sonnet-5
      variant: low

  personal:
    title:
      model: openai/gpt-5.6-luna
    compaction:
      model: opencode/deepseek-v4-flash
    general:
      model: openai/gpt-5.6-luna
      variant: high
    explore:
      model: openai/gpt-5.6-luna
      variant: low
    coder:
      model: openai/gpt-5.6-luna
      variant: xhigh
    commit:
      model: openai/gpt-5.6-luna
      variant: medium
    researcher:
      model: openai/gpt-5.6-luna
      variant: high
    reviewer:
      model: openai/gpt-5.6-sol
      variant: low
    upgradeAnalyst:
      model: openai/gpt-5.6-terra
      variant: high
