# Zinit - Modern zsh plugin manager
# Community-recommended alternative to Oh-My-Zsh with better performance and automation
["zinit.git"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/zinit.git"
    refreshPeriod = "168h"
