---
views:
  # Optimized containers view - prioritize essential info and resource usage
  v1/pods:
    sortColumn: NAMESPACE:desc
    columns:
    - NAME
    - STATUS
    - READY
    - NAMESPACE
    - "%CPU/L|R"
    - "%MEM/L|R"
    - AGE
    - RESTARTS|R

  # Optimized events view - hide SUBOBJECT and SOURCE columns to make MESSAGE more visible
  events:
    sortColumn: LAST SEEN:asc
    columns:
    - LAST SEEN
    - TYPE
    - REASON
    - OBJECT
    - MESSAGE
